kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"] 




     #"apps","rbac.authorization.k8s.io/v1","batch"]
     #deployment","pod","service"]
     #get","apply","delete","watch","patch","create"]